apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-pv-claim
  namespace: ci
  labels:
    app: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gitlab
  namespace: ci
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: gitlab
        app: gitlab
        node: gitlab_server
    spec:
      containers:
      - name: gitlab
        image: sameersbn/gitlab:10.6.4
        securityContext:
          runAsUser: 0
        env:
        - name: TZ
          value: Europe/Berlin
        - name: GITLAB_TIMEZONE
          value: Berlin
        - name: DEBUG
          value: "false"

        - name: GITLAB_SECRETS_DB_KEY_BASE
          value: P26qS5+Csz50Dkd0DLM2oN9owVBFg0PB
        - name: GITLAB_SECRETS_SECRET_KEY_BASE
          value: KVaMTKLAIElEp0s4L02c1O9JCP0Rfapb
        - name: GITLAB_SECRETS_OTP_KEY_BASE
          value: nXJJ358Qnci0yF9qpAsLrF2vImaoFR03

        - name: GITLAB_ROOT_PASSWORD
          value: password
        - name: GITLAB_ROOT_EMAIL
          value: root@example.com

        - name: GITLAB_HOST
          value: gitlab.ci
        - name: GITLAB_PORT
          value: "80"
        - name: GITLAB_SSH_HOST
          value: "gitlab.ci"
        - name: GITLAB_SSH_PORT
          value: "22"

        - name: GITLAB_NOTIFY_ON_BROKEN_BUILDS
          value: "true"
        - name: GITLAB_NOTIFY_PUSHER
          value: "false"

        - name: GITLAB_BACKUP_SCHEDULE
          value: daily
        - name: GITLAB_BACKUP_TIME
          value: 01:00

        - name: DB_TYPE
          value: postgres
        - name: DB_HOST
          value: gitlab-postgresql
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: gitlab
        - name: DB_PASS
          value: password
        - name: DB_NAME
          value: gitlabhq_production

        - name: REDIS_HOST
          value: gitlab-redis
        - name: REDIS_PORT
          value: "6379"

        - name: SMTP_ENABLED
          value: "false"
        - name: SMTP_DOMAIN
          value: ""
        - name: SMTP_HOST
          value: ""
        - name: SMTP_PORT
          value: ""
        - name: SMTP_USER
          value: ""
        - name: SMTP_PASS
          value: ""
        - name: SMTP_STARTTLS
          value: "true"
        - name: SMTP_AUTHENTICATION
          value: login
        - name: IMAP_ENABLED
          value: "false"
        - name: IMAP_HOST
          value: imap.gmail.com
        - name: IMAP_PORT
          value: "993"
        - name: IMAP_USER
          value: mailer@example.com
        - name: IMAP_PASS
          value: password
        - name: IMAP_SSL
          value: "true"
        - name: IMAP_STARTTLS
          value: "false"
        ports:
        - name: http
          containerPort: 80
        - name: ssh
          containerPort: 22
        readinessProbe:
          httpGet:
            path: /users/sign_in
            port: 80
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 2
          failureThreshold: 5
        volumeMounts:
        - mountPath: /home/git/data
          name: data
        resources:
          requests:
            cpu: 500m
            memory: 1500Mi
          limits:
            cpu: 2
            memory: 4Gi
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: gitlab-pv-claim
